// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutTracker.Data;

#nullable disable

namespace WorkoutTracker.Migrations
{
    [DbContext(typeof(WorkoutTrackerDbContext))]
    [Migration("20241212095714_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutTracker.Data.Entities.DayOfSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SplitId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DaysOfSplits");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SplitToString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekEnd")
                        .HasColumnType("integer");

                    b.Property<int>("WeekStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateWorkout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfSplitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayOfSplitId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Exercise", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Entities.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Workout", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Entities.DayOfSplit", null)
                        .WithMany("Workouts")
                        .HasForeignKey("DayOfSplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.DayOfSplit", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
